import XCTest
@testable import VocatecaCore

final class YouTubeExplorerLibrarySaveTests: XCTestCase {

    func testSaveWritesMarkdownAndMarksEpisodeDone() async throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }

        let dbURL = tmp.appendingPathComponent("state.sqlite")
        let watchlistURL = tmp.appendingPathComponent("watchlist.yaml")
        let outputRoot = tmp.appendingPathComponent("output")
        let store = try StateStore(databaseURL: dbURL)

        let transcript = ExtractedTranscript(
            videoID: "abc123",
            title: "Test Video",
            channelID: "UCxyz",
            channelHandle: "@testchannel",
            segments: [
                TranscriptionSegment(start: 0, end: 2, text: "Hello", speaker: nil),
                TranscriptionSegment(start: 2, end: 4, text: "World", speaker: nil),
            ],
            language: "en",
            source: .captions
        )

        let result = try await YouTubeExplorerLibrarySave.save(
            transcript,
            store: store,
            watchlistURL: watchlistURL,
            outputRoot: outputRoot,
            settings: Settings()
        )

        XCTAssertTrue(result.isNew)
        let episode = try store.episode(guid: result.guid)
        XCTAssertEqual(episode?.status, "done")
        XCTAssertNotNil(episode?.transcriptPath)
        let mdURL = URL(fileURLWithPath: episode!.transcriptPath!)
        let contents = try String(contentsOf: mdURL, encoding: .utf8)
        XCTAssertTrue(contents.contains("Hello"))
        XCTAssertTrue(contents.contains("World"))
    }

    func testSaveIsIdempotentOnDuplicateVideo() async throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = try StateStore(databaseURL: tmp.appendingPathComponent("state.sqlite"))
        let transcript = ExtractedTranscript(videoID: "dup1", title: "Dup", channelID: nil,
                                              channelHandle: nil,
                                              segments: [TranscriptionSegment(start: 0, end: 1, text: "x", speaker: nil)],
                                              language: nil, source: .captions)
        let first = try await YouTubeExplorerLibrarySave.save(
            transcript, store: store, watchlistURL: tmp.appendingPathComponent("watchlist.yaml"),
            outputRoot: tmp.appendingPathComponent("output"), settings: Settings())
        let second = try await YouTubeExplorerLibrarySave.save(
            transcript, store: store, watchlistURL: tmp.appendingPathComponent("watchlist.yaml"),
            outputRoot: tmp.appendingPathComponent("output"), settings: Settings())
        XCTAssertEqual(first.guid, second.guid)
        XCTAssertFalse(second.isNew)
    }

    func testSaveWritesVttAndCsvSidecarsWhenEnabled() async throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = try StateStore(databaseURL: tmp.appendingPathComponent("state.sqlite"))
        var settings = Settings()
        settings.saveVtt = true
        settings.saveCsv = true
        let transcript = ExtractedTranscript(videoID: "sidecars1", title: "Sidecars", channelID: nil,
                                              channelHandle: nil,
                                              segments: [TranscriptionSegment(start: 0, end: 1, text: "x", speaker: nil)],
                                              language: nil, source: .captions)
        let result = try await YouTubeExplorerLibrarySave.save(
            transcript, store: store, watchlistURL: tmp.appendingPathComponent("watchlist.yaml"),
            outputRoot: tmp.appendingPathComponent("output"), settings: settings)
        let episode = try store.episode(guid: result.guid)
        let mdURL = URL(fileURLWithPath: episode!.transcriptPath!)
        let vttURL = mdURL.deletingPathExtension().appendingPathExtension("vtt")
        let csvURL = mdURL.deletingPathExtension().appendingPathExtension("csv")
        XCTAssertTrue(FileManager.default.fileExists(atPath: vttURL.path))
        XCTAssertTrue(FileManager.default.fileExists(atPath: csvURL.path))
    }

    // MARK: - FIX 1: auto-generated captions must not be persisted as manual provenance

    func testSaveWithAutoGeneratedCaptionsPersistsAutoProvenance() async throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = try StateStore(databaseURL: tmp.appendingPathComponent("state.sqlite"))
        let transcript = ExtractedTranscript(videoID: "auto1", title: "Auto", channelID: nil,
                                              channelHandle: nil,
                                              segments: [TranscriptionSegment(start: 0, end: 1, text: "x", speaker: nil)],
                                              language: nil, source: .captions, captionsAuto: true)
        let result = try await YouTubeExplorerLibrarySave.save(
            transcript, store: store, watchlistURL: tmp.appendingPathComponent("watchlist.yaml"),
            outputRoot: tmp.appendingPathComponent("output"), settings: Settings())
        let episode = try store.episode(guid: result.guid)
        XCTAssertEqual(episode?.transcriptOrigin, "captions:auto")
    }

    func testSaveWithManualCaptionsPersistsManualProvenance() async throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = try StateStore(databaseURL: tmp.appendingPathComponent("state.sqlite"))
        let transcript = ExtractedTranscript(videoID: "manual1", title: "Manual", channelID: nil,
                                              channelHandle: nil,
                                              segments: [TranscriptionSegment(start: 0, end: 1, text: "x", speaker: nil)],
                                              language: nil, source: .captions, captionsAuto: false)
        let result = try await YouTubeExplorerLibrarySave.save(
            transcript, store: store, watchlistURL: tmp.appendingPathComponent("watchlist.yaml"),
            outputRoot: tmp.appendingPathComponent("output"), settings: Settings())
        let episode = try store.episode(guid: result.guid)
        XCTAssertEqual(episode?.transcriptOrigin, "captions:manual")
    }

    func testSaveWithEngineSourceUsesAsrMethod() async throws {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = try StateStore(databaseURL: tmp.appendingPathComponent("state.sqlite"))
        let transcript = ExtractedTranscript(videoID: "engine1", title: "Engine", channelID: nil,
                                              channelHandle: nil,
                                              segments: [TranscriptionSegment(start: 0, end: 1, text: "x", speaker: nil)],
                                              language: nil, source: .engine)
        let result = try await YouTubeExplorerLibrarySave.save(
            transcript, store: store, watchlistURL: tmp.appendingPathComponent("watchlist.yaml"),
            outputRoot: tmp.appendingPathComponent("output"), settings: Settings())
        let episode = try store.episode(guid: result.guid)
        XCTAssertTrue(episode?.transcriptOrigin?.hasPrefix("asr:") == true)
    }
}
