import Foundation

// MARK: - TranscriptOrigin

/// Records **how** an episode's transcript was derived, so every item can show
/// its provenance (which speech-to-text engine + model, or that it came from the
/// source — and if so whether the captions were auto-generated by the platform
/// or provided by the author).
///
/// **Engine-agnostic by design.** The ASR case carries a free-form `engine`
/// identifier (`"whisper"`, `"qwen3-asr"`, …) so adding a new transcription
/// engine needs no change here or in the pipeline — the new `Transcriber` just
/// tags its result with `.asr(engine:model:)`. Nothing on the transcription path
/// assumes a specific engine.
///
/// Persisted as a compact string in the `episodes.transcript_origin` column
/// (see ``storageString`` / ``parse(_:)``) and surfaced to the user via
/// ``displayLabel``.
public struct TranscriptOrigin: Sendable, Equatable {

    /// The broad derivation method.
    public enum Method: String, Sendable, Equatable {
        /// Text taken from the source's own caption/subtitle track.
        case captions
        /// Text produced locally by a speech-to-text engine (Whisper, Qwen, …).
        case asr
        /// Text extracted from an image via on-device OCR (Instagram posts).
        case ocr
    }

    /// For ``Method/captions``: who authored the caption track.
    public enum CaptionKind: String, Sendable, Equatable {
        /// Machine-generated by the platform (e.g. YouTube auto-captions).
        case auto
        /// Human-authored / uploaded by the creator.
        case manual
    }

    public let method: Method
    /// Set only when `method == .captions`.
    public let captionKind: CaptionKind?
    /// Set only when `method == .asr` — the engine that ran (`"whisper"`,
    /// `"qwen3-asr"`, …). Free-form so new engines need no change here.
    public let engine: String?
    /// Set only when `method == .asr` — the model identifier that ran.
    public let model: String?
    /// Set only when `method == .asr` — an optional engine-specific fast flag.
    public let fastMode: Bool?

    public init(method: Method,
                captionKind: CaptionKind? = nil,
                engine: String? = nil,
                model: String? = nil,
                fastMode: Bool? = nil) {
        self.method = method
        self.captionKind = captionKind
        self.engine = engine
        self.model = model
        self.fastMode = fastMode
    }

    // MARK: - Convenience constructors

    public static func captions(_ kind: CaptionKind) -> TranscriptOrigin {
        TranscriptOrigin(method: .captions, captionKind: kind)
    }

    /// Provenance for any local speech-to-text engine.
    public static func asr(engine: String, model: String, fastMode: Bool = false) -> TranscriptOrigin {
        TranscriptOrigin(method: .asr, engine: engine, model: model, fastMode: fastMode)
    }

    /// Convenience for the Whisper engine (thin wrapper over ``asr(engine:model:fastMode:)``).
    public static func whisper(model: String, fastMode: Bool = false) -> TranscriptOrigin {
        .asr(engine: "whisper", model: model, fastMode: fastMode)
    }

    public static let ocr = TranscriptOrigin(method: .ocr)

    // MARK: - Human-readable label

    /// A short user-facing description, e.g. "Captions · author-provided",
    /// "Whisper · large-v3-turbo", or "Qwen3-ASR · <model>".
    public var displayLabel: String {
        switch method {
        case .captions:
            let who = (captionKind == .manual) ? "author-provided" : "auto-generated"
            return "Captions · \(who)"
        case .asr:
            var s = Self.engineDisplayName(engine ?? "")
            if let m = model, !m.isEmpty { s += " · \(Self.cleanModelName(m))" }
            if fastMode == true { s += " · fast" }
            return s
        case .ocr:
            return "Image OCR · Apple Vision"
        }
    }

    /// Presentable engine name for the ASR case (falls back to the raw id).
    static func engineDisplayName(_ engine: String) -> String {
        switch engine.lowercased() {
        case "whisper", "whisperkit":  return "Whisper"
        case "qwen3-asr", "qwen":      return "Qwen3-ASR"
        case "parakeet":               return "Parakeet"
        case "":                       return "Speech-to-text"
        default:                       return engine
        }
    }

    /// Strips the HuggingFace repo prefix WhisperKit uses so the model reads
    /// cleanly (`openai_whisper-large-v3-turbo` → `large-v3-turbo`). Other
    /// engines' model ids pass through unchanged.
    static func cleanModelName(_ raw: String) -> String {
        var m = raw
        for prefix in ["openai_whisper-", "openai/whisper-", "whisper-"] where m.hasPrefix(prefix) {
            m = String(m.dropFirst(prefix.count))
            break
        }
        return m
    }

    // MARK: - Compact storage (DB column + round-trip)

    /// Compact, stable serialization for the `transcript_origin` column.
    ///
    /// - captions → `"captions:auto"` / `"captions:manual"`
    /// - asr      → `"asr:<engine>:<model>"` (+ `":fast"`), e.g.
    ///              `"asr:whisper:large-v3-turbo"`, `"asr:qwen3-asr:<model>"`
    /// - ocr      → `"ocr"`
    public var storageString: String {
        switch method {
        case .captions:
            return "captions:\((captionKind ?? .auto).rawValue)"
        case .asr:
            var s = "asr:\(engine ?? "")\(model.map { ":\($0)" } ?? ":")"
            if fastMode == true { s += ":fast" }
            return s
        case .ocr:
            return "ocr"
        }
    }

    /// Parses a ``storageString`` back into a `TranscriptOrigin`; `nil` on empty
    /// or unrecognised input. Also accepts the legacy `"whisper:<model>[:fast]"`
    /// form written before the engine-agnostic `asr:` layout.
    public static func parse(_ raw: String?) -> TranscriptOrigin? {
        guard let raw, !raw.isEmpty else { return nil }
        let parts = raw.split(separator: ":", omittingEmptySubsequences: false).map(String.init)
        switch parts.first {
        case "captions":
            let kind = (parts.count > 1 && parts[1] == "manual") ? CaptionKind.manual : .auto
            return .captions(kind)
        case "asr":
            let engine = parts.count > 1 ? parts[1] : ""
            let model  = parts.count > 2 ? parts[2] : ""
            let fast   = parts.contains("fast")
            return .asr(engine: engine, model: model, fastMode: fast)
        case "whisper":   // legacy layout: whisper:<model>[:fast]
            let model = parts.count > 1 ? parts[1] : ""
            let fast  = parts.contains("fast")
            return .whisper(model: model, fastMode: fast)
        case "ocr":
            return .ocr
        default:
            return nil
        }
    }
}
